name: Build RustDesk for Windows (Flutter)

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "nightly"

env:
  RUST_VERSION: "1.75"
  FLUTTER_VERSION: "3.24.5"
  LLVM_VERSION: "15.0.6"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.3"
  TAG_NAME: "${{ github.event.inputs.upload-tag }}"

jobs:
  build-for-windows-flutter:
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Install dependencies via vcpkg
        run: |
          $env:VCPKG_DEFAULT_HOST_TRIPLET = "x64-windows-static"
          & "$env:VCPKG_ROOT\vcpkg" install --triplet x64-windows-static --x-install-root="$env:VCPKG_ROOT\installed"

      - name: Build RustDesk (Flutter)
        run: |
          python .\build.py --flutter --portable --hwcodec --vram --skip-portable-pack
          Move-Item .\flutter\build\windows\x64\runner\Release .\rustdesk -Force

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: rustdesk
